### ISSUE TITLE
Human data error

### ISSUE THREAD

**Issue by Boltzz98** [bicciatolab/Circr#2]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'c_name'

Keep getting this error for both human genomes. Wonder why?

**Comment by Jimmy-A-Caroli** [comment]
Hello, thanks for the feedback.

From the error, it seems that the key "c_name" is not recognized. 
This key is used only when coordinates are not provided and thus exons location needs to be calculated by the software.
However, it weird that this happens. Do you mind providing the line of code you used to launch the software?
Also, did you check that all the required packages are correctly installed?
While processing the exons, a pybedtools call is made, and that can cause problems downstream if the result output is empty.

**Comment by Boltzz98** [comment]
Hi there. Thanks for the fast reply.

It seems I have solved the problem by inputting more queries into the bed file (more coordinates) and run the program. 
The error somehow didn't show up then.

Although, now I'm getting a different kind of error which is:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py", line 3361, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 76, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 108, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 3

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/media/ubuntu2004/Backup_Plus/Circr-main/Circr/Circr.py", line 618, in <module>
    main(args.input,
  File "/media/ubuntu2004/Backup_Plus/Circr-main/Circr/Circr.py", line 548, in main
    interactions = filter_interactions(valid_interactions, AGO, table)
  File "/media/ubuntu2004/Backup_Plus/Circr-main/Circr/Circr.py", line 493, in filter_interactions
    validated = val_intersected.loc[val_intersected[3] == val_intersected.iloc[:,-3]]
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py", line 3458, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/lib/python3.8/dist-packages/pandas/core/indexes/base.py", line 3363, in get_loc
    raise KeyError(key) from err
KeyError: 3



And this the command I used:

python3 /media/ubuntu2004/Backup_Plus/Circr-main/Circr/Circr.py -i 12hrs.bed -s human -v hg38  -o 12hrs.csv

It'll be good if you can check out why this error persist. 
Thanks.

**Comment by AdamuUu** [comment]
I have the same error. It works for the test data for mouse, nevertheless still `KeyError: 3 `for human, no matter if hg39 nor hg38 still occures. Moreover, currently it's impossible to run this tool. It's written using older version of pandas with the use of `append` which is deprecated. Latest pandas uses concat instead. To solve this, you can install older version of pandas: `pip install pandas==1.5.0 ` and add 
```
import pkg_resources
pkg_resources.require("pandas==1.5.0")
```
at the beginning of Circ.py if necessary but the tool won't work anyway because of different error. It took me almost two days to figure everything out and still no progres... :(
